### ISSUE TITLE
Support hyper 0.10

### ISSUE THREAD

**Issue by fkautz** [sfackler/hyper-openssl#1]
A new branch of hyper is currently in development. It includes removing openssl as a direct dependency in favor of solutions like hyper-openssl and hyper-tls. It also removes the cookie dependency which depends directly on rust-openssl.

**Comment by sfackler** [comment]
Yep, shouldn't take more than a version bump in the Cargo.toml when the release is published.

**Comment by fkautz** [comment]
Great. Also, a little bit of weirdness in the repo.

master is set as 0.10.x in Cargo.toml
0.10.x  branch is currently set as 0.9.14

**Comment by sfackler** [comment]
Released 0.2 with Hyper 0.10 support
