### ISSUE TITLE
disable_verification not work

### ISSUE THREAD

**Issue by sapsan4eg** [sfackler/hyper-openssl#13]
Hi, this flag `disable_verification` not work. That this flag would work, you need to pass the parameter ssl::SSL_VERIFY_NONE to the connector. Something like that:
```
let mut connector = try!(SslConnectorBuilder::new(SslMethod::tls()));
connector.builder_mut().set_verify(ssl::SSL_VERIFY_NONE);
let connector = connector.build();
Ok(OpensslClient::from(connector))
```

**Comment by sfackler** [comment]
You'll need to call [`OpensslClient::danger_disable_hostname_verification`](https://docs.rs/hyper-openssl/0.2.6/hyper_openssl/struct.OpensslClient.html#method.danger_disable_hostname_verification) as well.

**Comment by sapsan4eg** [comment]
Before writing this post I checked so does not work. Without this `connector.builder_mut().set_verify(ssl::SSL_VERIFY_NONE);` method `SslConnector.danger_connect_without_providing_domain_for_certificate_verification_and_server_name_indication` not work.

**Comment by sfackler** [comment]
Sure - you need to do both of those things if you want to totally disable certificate verification.

**Comment by sapsan4eg** [comment]
I have problem with self signed certificate. And this is only way.

**Comment by sfackler** [comment]
I'm not sure I understand what the issue is? This should work just fine:

```rust
let mut builder = SslConnectorBuilder::new().unwrap();
builder.builder_mut().set_verify(SSL_VERIFY_NONE);
let mut connector = OpensslClient::from(builder.build());
connector.danger_disable_hostname_verification();
```

**Comment by sfackler** [comment]
This is not the only way, FYI. You can tell OpenSSL to trust your self signed certificate:

```
let mut builder = SslConnectorBuilder::new().unwrap();
builder.builder_mut().set_ca_file("my_cert.pem").unwrap();
let mut connector = OpensslClient::from(builder.build());
```

**Comment by sapsan4eg** [comment]
Thank you @sfackler . This is work 
```
let mut builder = SslConnectorBuilder::new().unwrap();
builder.builder_mut().set_verify(SSL_VERIFY_NONE);
let mut connector = OpensslClient::from(builder.build());
connector.danger_disable_hostname_verification();
```
You can close issue. Maybe we should add examples?

**Comment by sfackler** [comment]
I would like to keep it hard to disable verification.
