### ISSUE TITLE
Add hook for updating the SSL implementation between connections

### ISSUE THREAD

**Issue by chriscoomber** [sfackler/hyper-openssl#15]
I'm trying to write some sort of simple wrapper to `OpensslClient` (and the same applies to `OpensslServer`) which runs some extra code at the start of each connection to change the SSL context in some way.

My specific use-case is that, with mutual TLS, the client's certificate/key might expire, and so I want some code to update this if necessary. It would be nice if I didn't have to rebuild the whole `OpensslClient` when this happens.

My proposal is something as simple as (pardon any typos):

```rust
pub struct OpensslClient {
    ...
    per_connection_update: Box<Fn(&mut openssl::ssl::Ssl) -> hyper::Result<()>>
}

impl<T> SslClient<T> for OpensslClient
    where T: NetworkStream + Clone + Sync + Send + Debug
{
    type Stream = SslStream<T>;

    fn wrap_client(&self, mut stream: T, host: &str) -> hyper::Result<SslStream<T>> {
        let mut conf = try!(self.connector.configure().map_err(|e| hyper::Error::Ssl(Box::new(e))));
        (self.per_connection_update)(conf)?;
        ...
    }
}
```

where this naturally defaults to `Box::new(|_| ())`.

Then I could use this like:

```rust
let updater = Box::new(move |ssl| {
   // Check for new certificates
});
let ssl_connector = ...;
let ssl_client = hyper_openssl::OpensslClient::new(ssl_connector, updater);    
```

**Comment by chriscoomber** [comment]
Alternatively, perhaps if I just had a `&mut OpensslClient` I'd be happy if there was a method to tweak its config permanently, instead of doing the per-connection stuff above.  I'd imagine that requires changes to `openssl` as well as `hyper-openssl`.

Naturally that would mean my wrapper would need to hold a `Mutex<OpensslClient>`, but that's fine as the `OpensslClient` already has blocking methods.

**Comment by sfackler** [comment]
The callback approach that's given the `Ssl` seems pretty reasonable to me! I'll make a PR tonight.

**Comment by chriscoomber** [comment]
@sfackler Is there any chance that this could be modified to return a `Result<(), Box<std::error::Error>>` (or some other error with a public constructor) instead of `Result<(), ErrorStack>`. For my usage, my callback can return all sorts of errors, and there's no way to convert these into an `ErrorStack` (as far as I can see).

**Comment by sfackler** [comment]
Hmm, it probably should return a `Box<Error>`. The right approach is I guess to add `ssl_callback2` and deprecate the old one.
