### ISSUE TITLE
 Unclear documentation in hyper_openssl 0.5.0 for server 

### ISSUE THREAD

**Issue by uncotion** [sfackler/hyper-openssl#21]
Hello,
I would like to write a simple server with hyper that can support HTTPS.
I choose hyper_openssl 0.5.0 to do this but documentation is Unclear.
Could you please give me an example?

**Comment by sfackler** [comment]
This library is only necessary for clients. On the server side, you'd just accept a TCP socket, use tokio-openssl to wrap that in an SslStream, and then pass that to https://docs.rs/hyper/0.11.27/hyper/server/struct.Http.html#method.serve_connection.

**Comment by uncotion** [comment]
@sfackler : thanks man.
