### ISSUE TITLE
Intended behaviour of set_callback/set_hostname

### ISSUE THREAD

**Issue by Lainera** [sfackler/hyper-openssl#34]
🌊 

[set_callback](https://docs.rs/hyper-openssl/latest/hyper_openssl/struct.HttpsConnector.html#method.set_callback) allows calling [set_hostname](https://docs.rs/openssl/0.10.42/openssl/ssl/struct.ConnectConfiguration.html#method.set_hostname) via passed `ConnectConfiguration`. 
However  `into_ssl` is called with the original, [unmodified hostname](https://github.com/sfackler/hyper-openssl/blob/master/src/lib.rs#L231), is this intended?

**Comment by sfackler** [comment]
I suppose that's intended? I don't know what other option there is given the API structure.

**Comment by Lainera** [comment]
Something along the lines of 
```
            let host = uri.host().ok_or("URI missing host")?;

            let config = inner.setup_ssl(&uri, host)?;
            let domain = config.servername(NameType::HOST_NAME)
                .unwrap_or(host)
                .to_owned();

            let ssl = config.into_ssl(&domain)?;
```
would consider servername over the supplied Uri.

Does that sound reasonable?  If so, I can make a PR

**Comment by sfackler** [comment]
The servername method does not retrieve the value set by set_hostname.

**Comment by Lainera** [comment]
Addressed by implementing custom [resolver](https://docs.rs/hyper/latest/hyper/client/connect/dns/index.html#resolvers-are-services)
