### ISSUE TITLE
OpensslServer non-file based certificate / key input

### ISSUE THREAD

**Issue by kallisti5** [sfackler/hyper-openssl#4]
It would be handy to have a non-file based (String) input of ssl certificates and keys.

https://docs.rs/hyper-openssl/0.2.1/hyper_openssl/struct.OpensslServer.html#method.from_files

from_strings, etc.

**Comment by sfackler** [comment]
It'd probably be easiest to just use openssl's APIs directly at that point:

```rust
extern crate openssl;
extern crate hyper_openssl;

use openssl::ssl::SslAcceptorBuilder;
use openssl::pkey::PKey;
use openssl::x509::X509;

fn main() {
    let key_pem = ...;
    let cert_chain_pem = ...;
    let key = PKey::private_key_from_pem(key_pem).unwrap();
    let cert_chain = X509::chain_from_pem(cert_chain_pem).unwrap();
    let acceptor = SslAcceptorBuilder::mozilla_intermediate(&key, &cert_chain[0], &cert_chain[1..])
        .unwrap()
        .build();
    let server = OpensslSever::from(acceptor);
}
```

**Comment by kallisti5** [comment]
It still would make a pretty handy convenience function though and reduce the surface area for having to rewrite applications due to changes in the openssl api.

**Comment by sfackler** [comment]
There are quite a lot of variants here. Is your key PEM or DER formatted? Do you have your leaf certificate and chain together in one file or split apart? Are they PEM or DER formatted? Are you using a PKCS#12 archive instead? Is the key encrypted?

The `from_files` method is there since it covers the the most common use case.

**Comment by sfackler** [comment]
I am also not planning on changing these APIs on the openssl side in the forseeable future.

**Comment by kallisti5** [comment]
MMkay.  I'd expect it to function the same as a file.  aka "whatever I could pass in via a file I could pass in via a string"

The solution mentioned works, it just puts the pain on the person leveraging the library vs the library itself.
