### ISSUE TITLE
Connecting to self signed https url

### ISSUE THREAD

**Issue by alwayscodingsince111970** [sfackler/hyper-openssl#5]
I'm trying to figure out how to connect to a self signed https url for a dev environment integration test. Unfortunately, even after setting the openssl context to SSL_VERIFY_NONE, I still get a refused connection. My code is below:

    extern crate hyper;
    extern crate hyper_openssl;
    extern crate openssl;
    extern crate diesel;
    
    use hyper::Client;
    use hyper::net::HttpsConnector;
    use openssl::ssl::*;

    #[test]
    fn test_new_uuid()
    {    
        let mut url = hyper::Url::parse("https://127.0.0.1/newUUID").unwrap();
        let _ = url.set_port(Some(20000));
    
        let mut ssl_connector_builder = SslConnectorBuilder::new(SslMethod::tls()).unwrap();
        {
            let mut ssl_context_builder = ssl_connector_builder.builder_mut();
            ssl_context_builder.set_verify(SSL_VERIFY_NONE);
        }
        let ssl_connector = ssl_connector_builder.build();
        let openssl_client = hyper_openssl::OpensslClient::from(ssl_connector);
        let connector = HttpsConnector::new(openssl_client);
        let client = Client::with_connector(connector);
    
        let response = client.get(url).send();
    
        assert!(response.unwrap().status == hyper::status::StatusCode::Ok);
    }

**Comment by sfackler** [comment]
The traditional approach here would be to configure OpenSSL to trust your certificate via the `set_ca_file` method rather than disabling verification.

**Comment by sfackler** [comment]
If you can't set things up that way, this should be helpful: https://github.com/sfackler/hyper-openssl/commit/31d7cea5abc9875fd85d40414d05d99908f288dd

**Comment by alwayscodingsince111970** [comment]
@sfackler Unfortunately I didn't have any luck with the first suggestion, so I tried using the method that you added. However, I keep getting ``error: no method named `danger_disable_hostname_verification` found for type `hyper_openssl::OpensslClient` in the current scope`` as a compile time error. I'm on the latest `hyper-openssl` crate.

Updated code below:

    extern crate hyper;
    extern crate hyper_openssl;
    extern crate openssl;
    extern crate diesel;
    
    use hyper::Client;
    use hyper::net::HttpsConnector;
    use openssl::ssl::*;
    
    #[test]
    fn test_new_uuid()
    {    
        let mut url = hyper::Url::parse("https://127.0.0.1/newUUID").unwrap();
        let _ = url.set_port(Some(20000));

        let openssl_client = hyper_openssl::OpensslClient::new().unwrap();
        openssl_client.danger_disable_hostname_verification(true);
        let connector = HttpsConnector::new(openssl_client);
        let client = Client::with_connector(connector);
    
        let response = client.get(url).send();

        assert!(response.unwrap().status == hyper::status::StatusCode::Ok);
    }

**Comment by sfackler** [comment]
That change hasn't been published in a release - you'll need to pull it from git to check it out. You will still need to either set a CA file or `VERIFY_NONE` as well.

**Comment by alwayscodingsince111970** [comment]
I'm using the release off master, and even tried switching to reading the cert and private key from a pkcs12 archive since that's what Iron https expects, but I still get a connection refused :(. I am on macOS 10.12.3, and have a build script that regenerates the pkcs12 file and adds it to the macOS Keychain.

    extern crate hyper;
    extern crate hyper_openssl;
    extern crate openssl;
    extern crate diesel;

    use std::io::Read;
    use hyper::Client;
    use hyper::net::HttpsConnector;
    use openssl::ssl::*;

    #[test]
    fn test_new_uuid()
    {    
        let mut url = hyper::Url::parse("https://127.0.0.1/newUUID").unwrap();
        let _ = url.set_port(Some(20000));

        let mut identity_file = std::fs::File::open("./ssl/identity.p12").unwrap();
        let mut pkcs12 = vec![];
        identity_file.read_to_end(&mut pkcs12).unwrap();
        let pkcs12 = openssl::pkcs12::Pkcs12::from_der(&pkcs12).unwrap();
        let identity = pkcs12.parse("testpass").unwrap();

        let mut ssl_connector_builder = SslConnectorBuilder::new(SslMethod::tls()).unwrap();
        {
        let mut ssl_context_builder = ssl_connector_builder.builder_mut();
            ssl_context_builder.set_verify(SSL_VERIFY_NONE);
            let _ = ssl_context_builder.set_certificate(&identity.cert);
            let _ = ssl_context_builder.set_private_key(&identity.pkey);
        }
        let ssl_connector = ssl_connector_builder.build();
        let mut openssl_client = hyper_openssl::OpensslClient::from(ssl_connector);
        {
            openssl_client.danger_disable_hostname_verification(true);
        }
        let connector = HttpsConnector::new(openssl_client);
        let client = Client::with_connector(connector);

        let response = client.get(url).send();

        assert!(response.unwrap().status == hyper::status::StatusCode::Ok);
    }

**Comment by sfackler** [comment]
Connection refused would imply an issue with the raw TCP connection, not with the SSL layer.

**Comment by swsnr** [comment]
@sfackler Thank you very much for the change; I was able to connect to an insecure internal site with the latest `master`.  Would you mind to publish a release including the change?

**Comment by sfackler** [comment]
Done!

**Comment by swsnr** [comment]
Thanks ❤
