### ISSUE TITLE
set ssl client ca path.

### ISSUE THREAD

**Issue by aep** [sfackler/hyper-openssl#6]
I can't figure out how to access the underlying Ssl to set a ca file or path with OpensslClient.

**Comment by sfackler** [comment]
You'll want to create an `SslConnectorBuilder` and configure it there:

```rust
use hyper_openssl::OpensslClient;
use hyper_openssl::openssl::ssl::SslConnectorBuilder;

let mut connector = SslConnectorBuilder::new().unwrap();
connector.builder_mut().set_ca_file(...).unwrap();
let connector = connector.build();
let client = OpensslClient::from(connector);
```

**Comment by sfackler** [comment]
Oops, probably replacing `SslConnectorBuilder` with `SslAcceptorBuilder` and `OpensslClient` with `OpensslServer`.

**Comment by aep** [comment]
aah thanks, i did not know these can be used for client connections too
